source 'https://rubygems.org'

ruby '~> 3.1.0'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'
gem 'rack-cors'
gem 'dotenv-rails'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end
